language: ruby

rvm:
- 2.6.3

before_script:
  bundle exec rake db:drop db:create db:migrate db:seed

script:
  bundle exec rubocop

notifications:
  email: false

env:
  MAILING_LIST_NAME="Travis Config Mailing List"
  EMAIL_USER=ci
  EMAIL_DOMAIN=travis-ci.org

