language: ruby

rvm:
- 2.6.3

services:
  -postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database events_management_test;' -U postgres
  - bundle exec rake db:drop db:create db:migrate db:seed

script:
  bundle exec rubocop

notifications:
  email: false

env:
  MAILGUN_API_KEY=key
  MAILING_LIST_NAME="Travis Config Mailing List"
  EMAIL_USER=ci
  EMAIL_DOMAIN=example.com
  ADMIN_PASSWORD=password

