version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.6.9
        environment: # add POSTGRES environment variables.
          POSTGRES_USER: rails
          POSTGRES_DB: events_management_test
          POSTGRES_PASSWORD: "rails"
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
      - ruby/rubocop-check
      - run:
          name: Database Schema Load
          command: bundle exec rails db:drop
      - run:
          name: Database Create
          command: bundle exec rails db:create
      - run:
          name: Database Schema Load
          command: bundle exec rails db:schema:load
      - run:
          name: Database Migrate
          command: bundle exec rails db:migrate
      - run:
          name: Database Seed
          command: bundle exec rails db:seed
